replicaCount: 1

image:
  repository: 891377152236.dkr.ecr.ap-northeast-2.amazonaws.com
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 250Mi
    cpu: 250m
  limits:
    memory: 250Mi
    cpu: 250m

service:
  - 172.20.30.10
  - 172.20.30.20
  - 172.20.30.30
  - 172.20.30.40

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

apps:
  - name: dev-was-intro
    imageTag: v1.0
  - name: dev-was-home
    imageTag: v1.1
  - name: dev-was-join
    imageTag: v1.0
  - name: dev-was-login
    imageTag: v0.1

enablePersistentVolume: true

nfs:
   server: fs-0b28aaa18b9db0a18.efs.ap-northeast-2.amazonaws.com
   path: /

persistentStorage:
   enabled: true
   mountPath: /data
   pvcName: efs-claim
