{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ .name }}
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ .name }}
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image.repository }}/{{ .name }}:{{ .imageTag }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
          volumeMounts:
          - name: persistent-storage
            mountPath: /data          
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10        
          resources:
            requests:
              memory: {{ $.Values.resources.requests.memory }}
              cpu: {{ $.Values.resources.requests.cpu }}
            limits:
              memory: {{ $.Values.resources.limits.memory }}
              cpu: {{ $.Values.resources.limits.cpu }}
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
{{- end }}
