apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-join
  labels:
    app: was-join
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was-join
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: was-join
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: was-join
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: was-join
      containers:
      - name: was-join
        image: 891377152236.dkr.ecr.ap-northeast-2.amazonaws.com/was-join:v0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: was-join-service
spec:
  selector:
    app: was-join
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
  clusterIP: 172.20.30.30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-was-join
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was-join
  targetCPUUtilizationPercentage: 50
