replicaCount: 1

image:
  repository: 891377152236.dkr.ecr.ap-northeast-2.amazonaws.com 
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 200Mi
    cpu: 100m

service:
  type: NodePort
  port: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

apps:
  - name: web-intro
    imageTag: v0.1
  - name: web-join
    imageTag: v0.1
  - name: web-login
    imageTag: v0.1
  - name: web-home
    imageTag: v0.3

enablePersistentVolume: true

nfs:
  server: fs-0b28aaa18b9db0a18.efs.ap-northeast-2.amazonaws.com
  path: /

persistentStorage:
  enabled: true
  mountPath: /data
  pvcName: efs-claim
