{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ .name }}
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ .name }}
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image.repository }}/{{ .name }}:{{ .imageTag }}
          ports:
          - containerPort: 80  # 포트를 80으로 수정
          livenessProbe:
            httpGet:
              path: /
              port: 80  # 포트를 80으로 수정
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 80  # 포트를 80으로 수정
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 30
          resources:
            requests:
              memory: 250Mi  # 메모리와 CPU 요청을 250Mi로 증가
              cpu: 250m
            limits:
              memory: 250Mi  # 메모리와 CPU 한계를 250Mi로 증가
              cpu: 250m
---
{{- end }}
