name: Dockerizing to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile/**/VERSION'

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORIES: "web-login web-join was-intro was-home"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push images to Amazon ECR
      run: |
        for repo in $ECR_REPOSITORIES; do
          VERSION=$(cat Dockerfile/$repo/VERSION)
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$repo:$VERSION -f Dockerfile/$repo/Dockerfile Dockerfile/$repo
          docker push ${{ steps.login-ecr.outputs.registry }}/$repo:$VERSION
        done
