name: Dockerizing to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile/**/*.VERSION'

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        run: |
          for path in $(find Dockerfile -type f -name "*.VERSION" -exec dirname {} \; | sort -u); do
            SERVICE_NAME=$(basename $path)
            VERSION=$(cat $path/VERSION)
            ECR_REPOSITORY="${SERVICE_NAME//-/_}"
            IMAGE_TAG="${VERSION}"

            echo "Building $SERVICE_NAME image with tag $IMAGE_TAG"
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $path/Dockerfile $path
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          done
