#web GitAction
name: Dockerizing to Amazon ECR

on:
  push:       
    branches:
      - main
    paths:
      - 'Dockerfile/**/VERSION'

env:
  AWS_REGION: ap-northeast-2        

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: List Dockerfiles
      id: list-dockerfiles
      run: |
        echo "::set-output name=dockerfiles::$(find Dockerfile -type f -name 'Dockerfile' -exec dirname {} \; | sort -u)"

    - name: Build and push images
      run: |
        for dockerfile in ${{ steps.list-dockerfiles.outputs.dockerfiles }}; do
          SERVICE_NAME=$(basename $(dirname $dockerfile))
          VERSION=$(cat $dockerfile/VERSION)
          IMAGE_TAG=$SERVICE_NAME:$VERSION
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_TAG -f $dockerfile/Dockerfile $dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_TAG
        done
