name: Dockerizing to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - '**/VERSION'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        AWS_REGION=ap-northeast-2
        ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        echo "::set-env name=AWS_REGION::$AWS_REGION"
        echo "::set-env name=ECR_REGISTRY::$ECR_REGISTRY"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Determine changed directories
      id: determine-changes
      run: |
        echo "::set-output name=directories::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs -I % dirname % | sort -u)"
      shell: bash

    - name: Build and push Docker images
      run: |
        for directory in ${{ steps.determine-changes.outputs.directories }}; do
          if [ -f "$directory/VERSION" ]; then
            image_name=$(basename $directory)
            version=$(cat $directory/VERSION)
            dockerfile="$directory/Dockerfile"
            
            docker buildx build -t $ECR_REGISTRY/$image_name:$version -f $dockerfile $directory --push
          fi
        done
