name: Dockerizing to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile/web-intro/VERSION'
      - 'Dockerfile/web-join/VERSION'
      - 'Dockerfile/web-login/VERSION'
      - 'Dockerfile/web-home/VERSION'
      - 'Dockerfile/was-intro/VERSION'
      - 'Dockerfile/was-join/VERSION'
      - 'Dockerfile/was-login/VERSION'
      - 'Dockerfile/was-home/VERSION'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        repo_name: [web-intro, web-home, web-login, web-join, was-intro, was-home, was-login, was-join]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get version from VERSION file
      id: get-version
      run: |
        VERSION=$(cat Dockerfile/${{ matrix.repo_name }}/VERSION)
        echo "::set-output name=version::$VERSION"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ matrix.repo_name }}
        IMAGE_TAG: ${{ steps.get-version.outputs.version }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile/${{ matrix.repo_name }}/Dockerfile Dockerfile/${{ matrix.repo_name }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
